import "~/styles/globals.css";

import { Inter } from "next/font/google";


import { TRPCReactProvider } from "~/trpc/react";
import { Navbar } from "./_components/navbar";
import { Splash } from "./_components/splash";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})



export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <TRPCReactProvider>
          <Navbar />
          <Splash />
          {children}</TRPCReactProvider>
      </body>
    </html>
  );
}
